### PR TITLE
[PR] Convert project to TypeScript

### LINKED ISSUE #162: Unable to Import in NextJS -> Bundled CSS
**Describe the bug**
Plyr is unable to be imported into a NextJS project as it contains bundled CSS.. Something that is not allowed as documented here.

https://github.com/zeit/next.js/blob/canary/errors/css-modules-npm.md

**To Reproduce**
Install plyr-react in a NextJS project
Import it to a file
Run the development server
See Error

**Expected behaviour**
I should be able to import the project, and supply the CSS separately to my file to avoid this incompatibility

### LINKED ISSUE #189: usage documentation
Hello,
I am sorry for asking but I dont find any good usage documentation for this.

### LINKED ISSUE #201: Typescript support
Is there any plan to have support for Typescript?

### LINKED ISSUE #261: Convert project to TypeScript
Hi 👋 ,

I was about to create a draft PR but I've noticed you've merged my fork into a new branch. I've created this issue to give you a heads up and also a run down of the changes.

Heads up:

I'm waiting on a new release from `plyr` since I [fixed](https://github.com/sampotts/plyr/pull/1900) a type issue yesterday.  Also, I'm still testing this is in a Next.js project so I'll let you know if everything works on my end.

The rundown:

* The project is written in Typescript and uses the types from the official repo. Fixes #201 
* `plyr-react` was not Next.js friendly since it imported the css styles within the component and that is no longer supported. Users will need to import the styles manually. Fixes #162 
* The component separates the `source` prop from `options` prop since original `Options` type does not include `source`.
* Configuration files are simplified. It's best to keep things simple but feel free to change it.

Thank you.

### Update

`Plyr` seems to work correctly with the latest version of Next.js.

### PR DESCRIPTION
**Pull request by iwatakeshi**
See #261 

This PR closes #261 and fixes #201, fixes #162, and fixes #189.

### CODE REVIEW

**Comment by chintan9** [comment]
Can you create another PR master ? Since v3 has another changes or you can wait couple of days to me release v3 another function like using docz instead of react-styleguidelist.

**Comment by iwatakeshi** [comment]
@chintan9 Sorry, I'm trying to match your branch 😅 .  I've just removed styleguidelist's config.

**Comment by iwatakeshi** [comment]
@chintan9 Double check for me but the branch in this PR should have all the changes you've added. If you have any more changes, just let me know and I'll add it back to my branch.

**Comment by chintan9** [comment]
@chintan9  I will let you know tomorrow.

**Pull request merged**
